include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    directives_ordering: true
    prefer_final_locals: true
    require_trailing_commas: true
